
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static amrex::Real small_dens;
static amrex::Real small_temp;
static std::string xl_ext_bc_type;
static std::string xr_ext_bc_type;
static std::string yl_ext_bc_type;
static std::string yr_ext_bc_type;
static std::string zl_ext_bc_type;
static std::string zr_ext_bc_type;
static amrex::Real fixed_dt;
static amrex::Real cfl;
static int do_acc;
static int print_fortran_warnings;
static int sum_interval;
static amrex::Real sum_per;
static int hard_cfl_limit;
