
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static int state_interp_order;
static int lin_limit_state_interp;
static int state_nghost;
static amrex::Real small_dens;
static amrex::Real small_temp;
static int ppm_predict_gammae;
static int ppm_reference_eigenvectors;
static int hybrid_riemann;
static int use_colglaz;
static int riemann_solver;
static int cg_maxiter;
static amrex::Real cg_tol;
static int cg_blend;
static int use_flattening;
static int dual_energy_update_E_from_e;
static amrex::Real dual_energy_eta1;
static amrex::Real dual_energy_eta2;
static amrex::Real dual_energy_eta3;
static int limit_fluxes_on_small_dens;
static int density_reset_method;
static int allow_negative_energy;
static int allow_small_energy;
static int first_order_hydro;
static std::string xl_ext_bc_type;
static std::string xr_ext_bc_type;
static std::string yl_ext_bc_type;
static std::string yr_ext_bc_type;
static std::string zl_ext_bc_type;
static std::string zr_ext_bc_type;
static int hse_zero_vels;
static int hse_interp_temp;
static int hse_reflect_vels;
static amrex::Real fixed_dt;
static amrex::Real initial_dt;
static amrex::Real dt_cutoff;
static amrex::Real max_dt;
static amrex::Real cfl;
static amrex::Real init_shrink;
static amrex::Real change_max;
static int do_acc;
static int print_fortran_warnings;
static int sum_interval;
static amrex::Real sum_per;
static int hard_cfl_limit;
static std::string job_name;
