
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

pp.query("small_dens", small_dens);
pp.query("small_temp", small_temp);
pp.query("xl_ext_bc_type", xl_ext_bc_type);
pp.query("xr_ext_bc_type", xr_ext_bc_type);
pp.query("yl_ext_bc_type", yl_ext_bc_type);
pp.query("yr_ext_bc_type", yr_ext_bc_type);
pp.query("zl_ext_bc_type", zl_ext_bc_type);
pp.query("zr_ext_bc_type", zr_ext_bc_type);
pp.query("fixed_dt", fixed_dt);
pp.query("cfl", cfl);
pp.query("do_acc", do_acc);
pp.query("print_fortran_warnings", print_fortran_warnings);
pp.query("sum_interval", sum_interval);
pp.query("sum_per", sum_per);
pp.query("hard_cfl_limit", hard_cfl_limit);
